# Generated by Django 5.1.5 on 2025-02-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="diary_images/", verbose_name="画像"
            ),
        ),
    ]
